### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by heraldsofruin** [BSData/wh40k-heralds-of-ruin#135]
As of today, with the release of GW Kill Team, this game system will be known as "Heralds of Ruin: Warhammer 40,000 Skirmish" - wasn't sure how to go about requesting this, so apologies if this is the wrong channel. Anyway, please help us avoid problems by changing the name if possible! Thank you!

**Comment by GenWilhelm** [comment]
Thanks for letting us know. I'll get that changed tonight.

**Comment by GenWilhelm** [comment]
I've updated the repo URL and readme, which I believe were the only places that referred to HoR as Kill Team. If I've missed any others, please let me know.

Note: an unfortunate side effect of renaming a repo means that anyone currently subscribed to the repo in BScribe will no longer receive new updates until they re-subscribe.

**Comment by heraldsofruin** [comment]
Thanks a lot :) I'll let the gang know!
