### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by Fraexov** [BSData/wh40k-heralds-of-ruin#145]
This was never completed and seems to have been abandoned. No one in the HoR community knows of anyone working with battlescribe for HoR since they first uploaded started work. 

I have made completely new files for HoR 9th edition that is on my computer and ready for upload. not sure if I am to take over here or make a new repository. The current version here is old and incomplete at least.

Best regards, Teis
Hyrrokin on Discord.

**Comment by amis92** [comment]
/add-via-pr repo=BSData/wh40k-heralds-of-ruin .github/workflows/chatops.yml:https://raw.githubusercontent.com/BSData/chatops/master/.github/workflows/chatops.yml .github/workflows/ci.yml:https://raw.githubusercontent.com/BSData/TemplateDataRepo/master/.github/workflows/ci.yml .github/workflows/publish-catpkg.yml:https://raw.githubusercontent.com/BSData/TemplateDataRepo/master/.github/workflows/publish-catpkg.yml

Add GH Actions

**Comment by amis92** [comment]
/invite

Let's try again after #146 was merged.

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/275274098)
**Error**:

**Comment by amis92** [comment]
/invite

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/275548728)
Invited @Fraexov with **push** access. Invite can be accepted on https://github.com/BSData/wh40k-heralds-of-ruin/invitations
